version: '3'
services:
 app:
  container_name: app
  image: ggmartinez/laravel:9-php7
  restart: unless-stopped
  tty: true
  ports:
    - 8000:8000
  volumes:
    - ./app:/app

 db:
  container_name: db
  image: mysql:5.7.32
  restart: unless-stopped
  tty: true
  ports:
   - 3306:3306
  environment:
   MYSQL_DATABASE: 2fa
   MYSQL_ROOT_PASSWORD: root1234
   SERVICE_TAGS: dev
   SERVICE_NAME: mysql
  volumes:
   - ./mysql:/var/lib/mysql/
   
